menu:
    Home: /
    Archives: /archives/
    Links: /links/
    About: /about/
    En: https://xiaopc.net/

favicon: /favicon.ico
logo: /logo.png
avatar: /avatar.jpg
likeqr: /wechat_like.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:
valineId: QWPJDsaiA2w1pYVMtdUaupan-MdYXbMMI
valineKey: bD3bvilfMLj1PdQxeG1klTm0


# Analytics
# google-analytics:
ga: UA-23646862-3

# Adsense
adsense: ca-pub-5846650450262128

# Copyright Infomation
startyear: 2008
