menu:
#    Home: /
    Archives: /archives/
    Links: /links.html
    Reviews: https://www.notion.so/08bd1851f8ed43339d87e7f764d437aa?v=8b7f92c3ace6450a95bf086fa81459f6
    About: /about
    Rss: /atom.xml

favicon: /favicon.ico
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus: xiaopc-1
duoshuo:

# Analytics
# google-analytics:
ga: UA-23646862-3

# Copyright Infomation
startyear: 2008
