menu:
    Home: /
    Archives: /archives/
    Links: /links/
    About: https://xpc.im/
    En: /blog-en/

favicon: /favicon.ico
logo: /logo.png
avatar: /avatar.jpg
likeqr: /wechat_like.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:
# valineId: QWPJDsaiA2w1pYVMtdUaupan-MdYXbMMI
# valineKey: bD3bvilfMLj1PdQxeG1klTm0


# Analytics
# google-analytics:
ga: G-KNHBVTCZSN

# google-tag-manager
gtm:

# Adsense
adsense:

# Copyright Infomation
startyear: 2008
